import { Layout } from "@/components/layout";
import { ArticleLayout } from "@/components/article-layout";

export default function OnChainProof() {
  return (
    <Layout>
      <ArticleLayout
        title="Cryptographic Proof on Solana"
        subtitle="Understanding the anatomy of a verifiable AI transaction."
        category="Platform"
        categoryLink="/platform/how-it-works"
        relatedLinks={[
          { title: "How It Works", href: "/platform/how-it-works" },
          { title: "Privacy Modes", href: "/platform/privacy-modes" },
          { title: "Security Architecture", href: "/platform/security" },
        ]}
      >
        <p>
          Verifiable AI means that you do not have to trust a centralized corporation to tell you the truth about your AI inference. Instead, mathematical proofs guarantee that the model you requested was the model that ran, and that the output has not been tampered with.
        </p>
        <p>
          Verifo anchors these proofs on the Solana blockchain, taking advantage of its high throughput and low fees to provide immutable records for every inference run on the network.
        </p>

        <h2>Anatomy of a Proof</h2>
        <p>
          Every completed task generates a JSON proof record containing the following fields:
        </p>

        <div className="not-prose my-8 bg-[hsl(28_40%_9%)] border border-border/20 rounded-xl p-6 font-mono text-sm shadow-xl overflow-x-auto text-white/90">
          <pre>
<span className="text-pink-400">"proof_id"</span>: <span className="text-green-300">"prf_8xj92nf73ks290d"</span>,
<span className="text-pink-400">"prompt_hash"</span>: <span className="text-green-300">"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"</span>,
<span className="text-pink-400">"output_hash"</span>: <span className="text-green-300">"8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4"</span>,
<span className="text-pink-400">"model_identifier"</span>: <span className="text-green-300">"meta-llama/Llama-3-70b-instruct"</span>,
<span className="text-pink-400">"node_signature"</span>: <span className="text-green-300">"sig_39fjd82..."</span>,
<span className="text-pink-400">"timestamp"</span>: <span className="text-purple-300">1715429811</span>,
<span className="text-pink-400">"wallet"</span>: <span className="text-green-300">"7Z1x...9Xp"</span>,
<span className="text-pink-400">"transaction_id"</span>: <span className="text-green-300">"5xJ..."</span>
          </pre>
        </div>

        <h3>Field Definitions</h3>
        <ul>
          <li><strong>Proof ID:</strong> A unique identifier generated by the Verifo router for this specific task.</li>
          <li><strong>Prompt Hash:</strong> A SHA-256 hash of the user's input. The hash acts as a fingerprint; anyone with the original prompt can verify it matches this hash, but the prompt itself cannot be reverse-engineered from the hash.</li>
          <li><strong>Output Hash:</strong> A SHA-256 hash of the AI's response.</li>
          <li><strong>Model Identifier:</strong> The exact model architecture and version that was executed.</li>
          <li><strong>Node Signature:</strong> A cryptographic signature from the assigned node, proving that this specific hardware provider generated the output (for a Compute Node) or forwarded and confirmed it (for a Relay Node).</li>
          <li><strong>Timestamp:</strong> The exact Unix timestamp of task completion.</li>
          <li><strong>Wallet:</strong> The Solana wallet address of the contributor node that ran the task, whichever tier it belongs to.</li>
          <li><strong>Transaction ID:</strong> The Solana blockchain transaction hash where this proof was permanently anchored.</li>
        </ul>

        <h2>Why Immutability Matters</h2>
        <p>
          In a standard AI setup, the provider can retroactively alter logs, censor outputs, or silently swap a high-tier model for a cheaper, lower-tier model to save compute costs.
        </p>
        <p>
          By generating a cryptographic proof and anchoring it on-chain, Verifo makes these actions impossible without detection. If a node attempts to return a response from a different model, the signatures will not match the requested constraints. If a provider alters a past output, the new hash will not match the immutable hash stored on Solana.
        </p>
      </ArticleLayout>
    </Layout>
  );
}
