import { Layout } from "@/components/layout";
import { ArticleLayout } from "@/components/article-layout";

export default function About() {
  return (
    <Layout>
      <ArticleLayout
        title="About Verifo"
        subtitle="Our mission to build the world's largest decentralized and mathematically verifiable AI network."
        category="Ecosystem"
        categoryLink="/ecosystem/roadmap"
        relatedLinks={[
          { title: "Roadmap", href: "/ecosystem/roadmap" },
          { title: "Governance", href: "/ecosystem/governance" },
          { title: "Developer API", href: "/ecosystem/developer-api" },
        ]}
      >
        <p>
          Verifo was founded on a simple observation: Artificial Intelligence is becoming the most critical infrastructure in the world, yet it is currently controlled by a handful of centralized corporations operating in total secrecy.
        </p>

        <h2>The Centralization Problem</h2>
        <p>
          Today's AI paradigm is deeply flawed:
        </p>
        <ul>
          <li><strong>Black Box Trust:</strong> Users cannot verify that an AI's output hasn't been secretly modified, censored, or generated by a cheaper, lower-quality model than the one they paid for.</li>
          <li><strong>Locked Infrastructure:</strong> Millions of high-end GPUs sit idle in gaming PCs and enterprise servers globally, while developers pay exorbitant markups to centralized cloud providers.</li>
          <li><strong>Altered History:</strong> AI output history can be changed or deleted by the provider without detection, destroying the concept of an objective audit trail.</li>
          <li><strong>Enterprise Risk:</strong> Companies building on closed APIs face severe vendor lock-in and must blindly trust that their data is not being used to train future competitor models.</li>
        </ul>

        <h2>The Verifo Vision</h2>
        <p>
          We are building a decentralized protocol where the infrastructure is community-owned, every output is mathematically verifiable, and participation is open to anyone.
        </p>
        <p>
          By decoupling the request layer from the compute layer, and introducing an independent verification layer, Verifo replaces corporate trust with cryptographic certainty.
        </p>

        <h2>Core Values</h2>
        <div className="space-y-6 mt-8">
          <div>
            <h3 className="text-xl font-bold mb-2">Openness</h3>
            <p className="text-muted-foreground">The network is permissionless. Anyone with a Solana wallet can submit a prompt, and anyone with a capable machine can connect it to the network and earn yields.</p>
          </div>
          
          <div>
            <h3 className="text-xl font-bold mb-2">Verifiability</h3>
            <p className="text-muted-foreground">Code is law, math is truth. We do not ask users to trust us; we provide the cryptographic proofs that allow them to verify every single interaction independently.</p>
          </div>
          
          <div>
            <h3 className="text-xl font-bold mb-2">Decentralization</h3>
            <p className="text-muted-foreground">There should be no single point of failure and no single point of control. A resilient intelligence network must be distributed globally.</p>
          </div>

          <div>
            <h3 className="text-xl font-bold mb-2">Privacy</h3>
            <p className="text-muted-foreground">Users should retain absolute sovereignty over their data. Public ledgers provide accountability, but encryption provides freedom. You decide what goes on-chain.</p>
          </div>
        </div>

        <hr className="my-12" />

        <p>
          <em>"Verifo is not just building a better API. We are building the foundational infrastructure for the next generation of human-AI interaction."</em>
        </p>
      </ArticleLayout>
    </Layout>
  );
}
